# Generated by Django 3.2.6 on 2021-10-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_likedislike_productlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductLike',
        ),
        migrations.RemoveField(
            model_name='likedislike',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='likedislike',
            name='object_id',
        ),
        migrations.AddField(
            model_name='likedislike',
            name='status',
            field=models.CharField(choices=[(-1, 'Dislike'), (1, 'Like')], max_length=20, null=True, verbose_name='وضعیت محصول'),
        ),
    ]
