# Generated by Django 3.2.6 on 2021-10-27 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211025_1200'),
        ('accounts', '0004_auto_20211027_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedislike',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.fishingproducts', verbose_name='محصول'),
        ),
    ]
