# Generated by Django 3.2.6 on 2021-10-27 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_likedislike_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedislike',
            name='status',
        ),
    ]
