# Generated by Django 3.2.6 on 2021-10-27 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_fishingproducts_like'),
        ('accounts', '0006_remove_likedislike_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeDislikeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LikeCount', models.IntegerField()),
                ('DislikeCount', models.IntegerField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.fishingproducts', verbose_name='محصول')),
            ],
        ),
    ]
