# Generated by Django 3.2.6 on 2021-11-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_fishingproducts_specials'),
        ('accounts', '0008_auto_20211027_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_by', to='products.FishingProducts', verbose_name='نشان شده ها'),
        ),
    ]
