# Generated by Django 3.2.6 on 2021-12-01 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_fishingproducts_favorites'),
        ('accounts', '0010_profilemodel_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.fishingproducts', verbose_name='محصول'),
        ),
    ]
