# Generated by Django 3.2.6 on 2021-12-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20211201_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='user',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='نام و نام خانوادگی'),
        ),
    ]
