# Generated by Django 3.2.6 on 2021-12-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_profilemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='location',
            field=models.CharField(max_length=300, verbose_name='موقعیت مکانی'),
        ),
    ]
