# Generated by Django 3.2.6 on 2021-12-04 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_profilemodel_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='birthday',
        ),
    ]
