# Generated by Django 3.2.6 on 2021-12-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_profilemodel_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
    ]
