# Generated by Django 3.2.6 on 2021-12-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_profilemodel_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='birthday',
            field=models.DateTimeField(),
        ),
    ]
