# Generated by Django 3.2.6 on 2021-12-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_profilemodel_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='email',
            field=models.EmailField(max_length=250, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='location',
            field=models.CharField(max_length=300, null=True, verbose_name='موقعیت مکانی'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='melicode',
            field=models.BigIntegerField(null=True, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='zipcode',
            field=models.BigIntegerField(null=True, verbose_name='کد پستی \u200d'),
        ),
    ]
