# Generated by Django 3.2.6 on 2021-12-17 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_fishingproducts_price_discounted'),
        ('accounts', '0028_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.fishingproducts', verbose_name='محصول'),
        ),
    ]
