# Generated by Django 3.2.6 on 2021-11-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, verbose_name='خریداری شده '),
        ),
        migrations.AlterField(
            model_name='cart',
            name='ordered_date',
            field=models.DateTimeField(verbose_name='زمان تحویل'),
        ),
    ]
