# Generated by Django 3.2.6 on 2021-10-04 06:59

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
            ],
        ),
        migrations.CreateModel(
            name='Dicty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Details', models.CharField(max_length=50, verbose_name='مشخصه')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='anonymous user', max_length=50, null=True, verbose_name='کاربر')),
                ('rating', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='امتیاز')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics/', verbose_name='عکس')),
            ],
        ),
        migrations.CreateModel(
            name='KeyVal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=240, verbose_name='مشخصه')),
                ('value', models.CharField(db_index=True, max_length=240, verbose_name='مقدار')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.dicty')),
            ],
        ),
        migrations.CreateModel(
            name='FishingProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='نام محصول')),
                ('descriptions', models.TextField(max_length=1000, verbose_name='توضیحات')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('numbers', models.IntegerField(blank=True, null=True, verbose_name='تعداد')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.categury')),
                ('image', models.ManyToManyField(to='products.Images')),
                ('rate', models.ForeignKey(blank=True, default='NA', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.feedback')),
                ('tags', taggit.managers.TaggableManager(help_text='برای جدا کردن تگ ها از "," استفاده کنید', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.fishingproducts'),
        ),
    ]
