# Generated by Django 3.2.6 on 2021-10-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211010_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', ' افزایشی'), ('1', 'کاهشی')], max_length=20, null=True, verbose_name='وضعیت ')),
            ],
        ),
    ]
