# Generated by Django 3.2.6 on 2021-10-25 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_fishingproducts_price_discounted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categury',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='dicty',
            options={'verbose_name': 'نوع محصول', 'verbose_name_plural': ' نوع محصولات'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'باز خورد', 'verbose_name_plural': 'باز خورد ها'},
        ),
        migrations.AlterModelOptions(
            name='fishingproducts',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محولات'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'عکس', 'verbose_name_plural': 'عکس ها'},
        ),
        migrations.AlterModelOptions(
            name='keyval',
            options={'verbose_name': 'مشخصه ی فنی', 'verbose_name_plural': 'مشخصات فنی'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'تگ', 'verbose_name_plural': 'تگ ها'},
        ),
        migrations.AlterField(
            model_name='fishingproducts',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.categury', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='fishingproducts',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده'),
        ),
        migrations.AlterField(
            model_name='fishingproducts',
            name='image',
            field=models.ManyToManyField(to='products.Images', verbose_name='عکس ها'),
        ),
        migrations.AlterField(
            model_name='fishingproducts',
            name='rate',
            field=models.ForeignKey(blank=True, default='NA', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.feedback', verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='fishingproducts',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='fishingproducts',
            name='tag',
            field=models.ManyToManyField(to='products.Tags', verbose_name='تگ ها'),
        ),
        migrations.AlterField(
            model_name='fishingproducts',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='اپدیت شده'),
        ),
    ]
