# Generated by Django 3.2.6 on 2021-10-27 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_auto_20211025_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingproducts',
            name='like',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='لایک'),
        ),
    ]
