# Generated by Django 3.2.6 on 2021-10-27 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20211027_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fishingproducts',
            old_name='dislike',
            new_name='dislikes',
        ),
        migrations.RenameField(
            model_name='fishingproducts',
            old_name='like',
            new_name='likes',
        ),
    ]
