# Generated by Django 3.2.6 on 2021-11-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20211027_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingproducts',
            name='special_offer',
            field=models.BooleanField(null=True, verbose_name='پیشنهاد شگفت انگیز'),
        ),
    ]
