# Generated by Django 3.2.6 on 2021-11-04 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_fishingproducts_special_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniCategury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categury')),
            ],
            options={
                'verbose_name': ' ریز دسته بندی',
                'verbose_name_plural': 'ریز دسته بندی ها',
            },
        ),
    ]
