# Generated by Django 3.2.6 on 2021-11-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_minicategury'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingproducts',
            name='picture',
            field=models.ImageField(default=2, upload_to='pics/', verbose_name='عکس های صفحع اصلی'),
            preserve_default=False,
        ),
    ]
