# Generated by Django 3.2.6 on 2021-11-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_fishingproducts_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categury',
            old_name='title',
            new_name='titles',
        ),
    ]
