# Generated by Django 3.2.6 on 2021-11-08 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_title_categury_titles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categury',
            old_name='titles',
            new_name='title',
        ),
    ]
