# Generated by Django 3.2.6 on 2021-11-08 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_titles_categury_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingproducts',
            name='minicategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.minicategury'),
        ),
    ]
