# Generated by Django 3.2.6 on 2021-11-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_fishingproducts_minicategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='categury',
            name='slug',
            field=models.SlugField(null=True, verbose_name='عنوان لاتین'),
        ),
    ]
