# Generated by Django 3.2.6 on 2021-11-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_categury_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='minicategury',
            name='slug',
            field=models.SlugField(null=True, verbose_name='عنوان لاتین'),
        ),
    ]
