# Generated by Django 3.2.6 on 2021-11-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_minicategury_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minicategury',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='عنوان لاتین'),
        ),
    ]
