# Generated by Django 3.2.6 on 2021-11-14 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_minicategury_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingproducts',
            name='kayvalue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.dicty', verbose_name='ویژگی'),
        ),
    ]
