# Generated by Django 3.2.6 on 2021-11-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_keyval_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyval',
            name='important',
            field=models.BooleanField(default=1, null=True, verbose_name='ویژگی مهم'),
        ),
    ]
