# Generated by Django 3.2.6 on 2021-11-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_keyval_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyval',
            name='important',
            field=models.BooleanField(default=2, null=True, verbose_name='ویژگی مهم'),
        ),
    ]
