# Generated by Django 3.2.6 on 2021-11-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_fishingproducts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishingproducts',
            name='descriptions',
            field=models.TextField(max_length=100000, verbose_name='توضیحات'),
        ),
    ]
