# Generated by Django 3.2.6 on 2021-11-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_fishingproducts_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingproducts',
            name='specials',
            field=models.ManyToManyField(related_name='specials', to='products.KeyVal', verbose_name='ویژگی های خاص'),
        ),
    ]
