# Generated by Django 3.2.6 on 2021-11-27 07:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0024_fishingproducts_specials'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingproducts',
            name='favorites',
            field=models.ManyToManyField(related_name='faves', to=settings.AUTH_USER_MODEL, verbose_name='علاقه مندی ها'),
        ),
    ]
