# Generated by Django 3.2.6 on 2021-12-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_fishingproducts_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainpageimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics/', verbose_name='عکس ها')),
            ],
        ),
    ]
