# Generated by Django 3.2.6 on 2021-12-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_mainpageimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingproducts',
            name='stock',
            field=models.BooleanField(default=1, verbose_name='موجود'),
        ),
    ]
