# Generated by Django 3.2.6 on 2021-12-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_fishingproducts_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishingproducts',
            name='price_discounted',
            field=models.IntegerField(verbose_name='قیمت با تخفیف'),
        ),
    ]
