# Generated by Django 3.2.6 on 2021-12-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_fishingproducts_price_discounted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishingproducts',
            name='price_discounted',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف'),
        ),
    ]
